#!/bin/bash

echo "index \t name  \t MBTI"
echo "1  \t JunYe \t ISTJ"
echo "2  \t JunYe \t ISTP"
echo "3  \t JunYe \t ESTP"
echo "4  \t JunYe \t ESTJ"
echo "5  \t Mario \t ISFJ"
echo "6  \t Mario \t ISFP"
echo "7  \t Mario \t ESFP"
echo "8  \t Mario \t ESFJ"
echo "9  \t Joel  \t INFJ"
echo "10 \t Joel  \t INFP"
echo "11 \t Joel  \t ENFP"
echo "12 \t Joel  \t ENFJ"
echo "13 \t Joel  \t INTJ"
echo "14 \t Joel  \t INTP"
echo "15 \t Joel  \t ENTP"
echo "16 \t John  \t ENTJ"
echo "17 \t John  \t ESFP"
echo "18 \t Peter \t ESFJ"
echo "19 \t Peter \t INFJ"
echo "20 \t Peter \t INFP"
echo "21 \t Peter \t ENFP"
echo "22 \t Eva   \t ESTJ"