#!/bin/bash

echo -e "index \t name  \t MBTI"
echo -e "1  \t JunYe \t ISTJ"
echo -e "2  \t JunYe \t ISTP"
echo -e "3  \t JunYe \t ESTP"
echo -e "4  \t JunYe \t ESTJ"
echo -e "5  \t Mario \t ISFJ"
echo -e "6  \t Mario \t ISFP"
echo -e "7  \t Mario \t ESFP"
echo -e "8  \t Mario \t ESFJ"
echo -e "9  \t Joel  \t INFJ"
echo -e "10 \t Joel  \t INFP"
echo -e "11 \t Joel  \t ENFP"
echo -e "12 \t Joel  \t ENFJ"
echo -e "13 \t Joel  \t INTJ"
echo -e "14 \t Joel  \t INTP"
echo -e "15 \t Joel  \t ENTP"
echo -e "16 \t John  \t ENTJ"
echo -e "17 \t John  \t ESFP"
echo -e "18 \t Peter \t ESFJ"
echo -e "19 \t Peter \t INFJ"
echo -e "20 \t Peter \t INFP"
echo -e "21 \t Peter \t ENFP"
echo -e "22 \t Eva   \t ESTJ"